data:extend({
    {
        type = "string-setting",
        name = "preferred-fuel",
        setting_type = "runtime-global",
        default_value = "coal",
        auto_trim = true,
        localised_name = "Prefered fuel",
        localised_description = "What fuel to insert into a burner without fuel.",
        order = "1-fuel-1-preferred",
    },
    {
        type = "int-setting",
        name = "min-fuel",
        setting_type = "runtime-global",
        default_value = 1,
        minimum_value = 1,
        auto_trim = true,
        localised_name = "Minimum fuel count",
        localised_description = "Insert more fuel if fuel count is lower than this amount.",
        order = "1-fuel-2-min",
    },
    {
        type = "int-setting",
        name = "max-fuel",
        setting_type = "runtime-global",
        default_value = 20,
        minimum_value = 1,
        auto_trim = true,
        localised_name = "Maximum fuel count",
        localised_description = "Remove fuel if fuel count is higher than this amount. (Useful when 2+ burner miners mine into each other.)",
        order = "1-fuel-3-max",
    },
    {
        type = "string-setting",
        name = "preferred-ammo",
        setting_type = "runtime-global",
        default_value = "piercing-rounds-magazine",
        auto_trim = true,
        localised_name = "Preferred ammo",
        localised_description = "What ammo to insert when a turret is out of ammo.",
        order = "2-ammo-1-preferred",
    },
    {
        type = "int-setting",
        name = "min-ammo",
        setting_type = "runtime-global",
        default_value = 10,
        minimum_value = 1,
        auto_trim = true,
        localised_name = "Minimum ammo count",
        localised_description = "Insert more ammo if ammo coount is lower than this amount.",
        order = "2-ammo-2-min",
    },
    {
        type = "int-setting",
        name = "max-item",
        setting_type = "runtime-global",
        default_value = 2000,
        minimum_value = 0,
        auto_trim = true,
        localised_name = "Maximum items",
        localised_description = "Maximum number of items to store of each type.",
        order = "3-limits-1-item",
    },
    {
        type = "int-setting",
        name = "max-liquid",
        setting_type = "runtime-global",
        default_value = 25000,
        minimum_value = 0,
        auto_trim = true,
        localised_name = "Maximum Liquid",
        localised_description = "Maximum amount of liquid to store of each type.",
        order = "3-limits-2-liquid",
    },
    {
        type = "int-setting",
        name = "min-item",
        setting_type = "runtime-global",
        default_value = 10,
        minimum_value = 0,
        auto_trim = true,
        localised_name = "Minimum items",
        localised_description = "Minimum number of items to store of each type. Only auto-fill machines with items when we have more then this amount.",
        order = "3-limits-3-min-item",
    },
    {
        type = "int-setting",
        name = "item-columns",
        setting_type = "runtime-global",
        default_value = 28,
        minimum_value = 1,
        auto_trim = true,
        localised_name = "Item columns",
        localised_description = "How many items to show on each row.",
        order = "4-gui-1-columns",
    },
    {
        type = "bool-setting",
        name = "ft-button",
        setting_type = "runtime-global",
        default_value = true,
        auto_trim = true,
        localised_name = "Show FT-button",
        localised_description = "Show the Furnace-template configuration button.",
        order = "4-gui-2-button",
    },
})